### ISSUE TITLE
DOI broken in Bioscales study page 

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#606] opened 2022-02-22 18:35 UTC
"Other Publications" Link looks odd to be pointing to OSTI for Bioscales. Also, clicking on the DOI takes you to an undefined DOI. @dehays can you help sort out what might be causing this?

![image](https://user-images.githubusercontent.com/7374085/155196466-6e99111f-530c-4bef-946a-d2e94f56f8cd.png)

**Comment by dehays** [comment] 2022-02-23 20:33
First - all three references to DOIs on the BioScales study page are the same DOI.  It is the DOI associated with the OSTI Award.  Going to the OSTI Award page is the correct behavior.  There are no DOIs here that are associated with either data sets or publications.

Second - The DOI link on the left of the study page and the link out from the "Dataset Citation" section both work.  There is an issue with the link out from the "Other publications" section.

**Comment by dehays** [comment] 2022-07-08 20:29
If this is still an issue, I suggest looking at 1) the attributes on the study JSON document and 2) how the data portal is building the study UI.  That likely means Montana on the metadata management (use the API to examine the study JSON) and Matt/Brandon from Kitware.  I recall there were some study values that were retrieved 'out of band' as short terms fixes to study displays - someone would need to look at the data portal app to see if that is related.

Assigning to Montana

**Comment by mslarae13** [comment] 2022-07-29 22:54
If i'm understanding this issue right. The only DOI that should be listed & is correct is Study : https://doi.org/10.46936/10.25585/60000017 

Having this same DOI for the data sets & publications is incorrect. So, these 2 should be replaced with correct DOIs.
I'm assuming Stan or Chris would have the DOI information for these if they exists.

**Comment by mslarae13** [comment] 2022-08-16 22:57
Checking in with @emileyfadrosh  before emailing Chris and Stan.

**Comment by emileyfadrosh** [comment] 2022-08-16 23:22
Thanks for checking @mslarae13 -- you are correct, only the DOI should be listed for data set citation. No publications yet. I think this was a hack for GSP. Please use https://doi.org/10.46936/10.25585/60000017 for the data set DOI.

**Comment by mslarae13** [comment] 2022-08-16 23:36
Thanks Emiley! So the DOI that's in publications need removed...
That link is broken for me? Says page not found?
Also, isn't that the project or proposal DOI? Not the dataset DOI?

**Comment by emileyfadrosh** [comment] 2022-08-17 12:33
Sorry, yes: the DOIs from JGI are proposal-level DOIs, not data set DOIs. Perhaps this needs to be updated in the schema to reflect the correct terms going forward? @mslarae13 @turbomam

**Comment by ssarrafan** [comment] 2022-09-01 18:15
@jeffbaumes moving to Sept but if nobody is working on it in the next 2 weeks please let me know

**Comment by jeffbaumes** [comment] 2022-09-01 18:53
The underlying cause and plan for resolution is #772. Please put that one in the Sep sprint.

**Comment by ssarrafan** [comment] 2022-09-01 18:58
> The underlying cause and plan for resolution is #772. Please put that one in the Sep sprint.

Ok I added 772.  Should it be assigned to Matt?

**Comment by jeffbaumes** [comment] 2022-09-01 19:06
> Ok I added 772. Should it be assigned to Matt?

Yes

**Comment by ssarrafan** [comment] 2022-09-01 20:39
This is a duplicate of #772 so closing this issue.

**Closed by ssarrafan** 2022-09-01 20:39 UTC
Labels: type: bug
