### ISSUE TITLE
Submission portal interface is "jumpy"

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#916] opened 2023-03-30 19:27 UTC
We had a couple people at the workshop (& @lamccue ) experience the data harmonizer interface being jumpy. When they click on a cell the screen jumps to the left, highlights all the cells, and they can't edit the cell they were on. It also sometimes throws them to the bottom of the sheet when they select a cell.

Will ask Lee Ann to try and take a screen recording.

One of the people at the workshop provided these specs for their system
Version 109.0.5414.119 (Official Build) (x86_64)
Mac OS Big Sur
Version 11.6.8
Chrome

**Comment by lamccue** [comment] 2023-03-30 20:09
I am on a mac, using chrome:
MacOS Monterey 12.6.3
Chrome Version 111.0.5563.64

I did a screen recording of this issue, which is too big to put here, but I put it in google drive here: https://drive.google.com/file/d/1b36hWe6I0aZSMjqavtxWSTIvodLrqXI1/view?usp=share_link

In this video, clicking on a single cell jumps to a highlight of three or four cells. Previously, I've seen it highlight all the way to then of the row. It is very sporadic behavior, happens randomly as far as I can tell.

**Comment by naglepuff** [comment] 2023-03-30 20:45
@pkalita-lbl have you ever seen this behavior before? I don't think I have, but I'll keep my eyes out for it. Would this be a core DH issue or is it something `nmdc-server` is doing?

**Comment by pkalita-lbl** [comment] 2023-03-30 21:19
No I have no idea. I don't believe I've ever seen this before. It could just as easily be a core DH thing or a `nmdc-server` thing. If you're not already looking at it feel free to assign to me and I can take a look.

**Comment by lamccue** [comment] 2023-03-31 15:49
Yep, I see the behavior on dev too @pkalita-lbl.  I put a clip on the google drive here: 
https://drive.google.com/file/d/1-xkHuScKjXddryw9jmMt-BdeuaAgOsFf/view?usp=share_link

When I was making this one, I noticed a couple times when I would double click on a cell, as if to enter a value, that it would jump to a different cell (a couple columns to the right, in the same row).  And a few times the clip shows the behavior of single clicking on a cell and having a series of cells highlighted.

**Comment by pkalita-lbl** [comment] 2023-03-31 16:47
Thanks. I'm able to reproduce this behavior on dev as well. I can't reproduce it with the same schema & data in a plain vanilla DataHarmonizer interface. So the issue must lie in the `nmdc-server` integration of DataHarmonizer. Still have no clue what's going on, but at least that eliminates some possibilities.

**Comment by lamccue** [comment] 2023-03-31 19:45
I do not think that it is high priority for GSP.  As far as I can tell, the behavior is very random,  happens infrequently, and does not actually inhibit someone from using the portal functions.

**Comment by mslarae13** [comment] 2023-04-14 23:22
https://drive.google.com/file/d/1rqQXHA5otLbcSkqnkNeWe9WwDoTqxC2Q/view?usp=sharing

**Comment by mslarae13** [comment] 2023-06-03 00:43
We had an ambassador testing out the portal and came across the same bug. See video here: https://drive.google.com/file/d/1U98ZJ2KDetsB4PxBwn3QaPnd6F2n-9T3/view?usp=drive_link 


How she described it: "I found that once I finished working on one cell and hit enter, the window turned somewhere else rather than staying where that cell was. The video recording is attached.
I am using Google Chrome Version 111.0.5563.146 (Official Build) (arm64)."

**Comment by ssarrafan** [comment] 2023-06-05 17:58
Asked @mslarae13 about this and it would be great to fix if Mike has time this sprint.  @jeffbaumes @naglepuff

**Comment by naglepuff** [comment] 2023-06-05 21:33
@mslarae13 @ssarrafan @pkalita-lbl 
I'm still struggling to reproduce this. I'm doing my best to try and follow the various screen recordings here, but it's difficult to know if I'm missing context. 

Starting from an empty data harmonizer sheet, what's the most consistent way to set this bug up? 

It looks like it happens once every few clicks/tabs/enters, but I haven't seen it in about 30 minutes of fiddling around in data harmonizer.

I'm on Ubuntu 20.04, testing with firefox and chrome. I doubt OS has anything to do with it though.

**Comment by pkalita-lbl** [comment] 2023-06-08 22:21
* Go to https://data-dev.microbiomedata.org/submission/86f8402b-f6cc-4622-be5d-9aabfde18c14/samples
* Scroll to the right to find the "isotope exposure/addition" column
* Attempt to edit the value of that column for any row. Once you hit enter you will lose your place. In my experience it's nearly impossible to edit most of the "right-most" columns.

**Closed** 2023-06-13 17:42 UTC
Labels: type: bug

**Comment by mslarae13** [comment] 2023-07-31 18:46
@pkalita-lbl  This is happening again.... :( 

https://drive.google.com/file/d/108Bxn1mhWd23YTCKmFAm5ciz_QWcjShE/view?usp=sharing
