### ISSUE TITLE
Multiomics: Alternative names is confusing

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#880] opened 2023-03-02 21:54 UTC
<img width="1065" alt="Screen Shot 2023-03-02 at 1 56 30 PM" src="https://user-images.githubusercontent.com/79225425/222567824-9669a480-886a-4220-817f-639cdb379b93.png">
Rename "Alternative Names" as "Alternative Names / Ids" and put it under GOLD and NCBI Project Accession

**Comment by pkalita-lbl** [comment] 2023-03-03 22:23
Closing as a duplicate of https://github.com/microbiomedata/issues/issues/107

**Closed by pkalita-lbl** 2023-03-03 22:23 UTC

**Comment by ssarrafan** [comment] 2023-03-14 22:55
tested on data-dev and confirm it's updated
<img width="871" alt="Screen Shot 2023-03-14 at 3 54 50 PM" src="https://user-images.githubusercontent.com/79225425/225160030-f13b6f0b-ce07-48f3-bb09-22c133ecf43c.png">
