### ISSUE TITLE
Handle study/consortium page with no PI information

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1064] opened 2023-10-06 21:36 UTC
Related to #1063

**Comment by mslarae13** [comment] 2023-11-07 21:09
Checked in with @marySalvi  done. Can we close?

**Comment by mslarae13** [comment] 2024-01-30 20:03
@naglepuff @marySalvi is this done? I don't remember moving it to the done column, but I did! But it isn't closed.

**Comment by mslarae13** [comment] 2024-02-19 20:50
@naglepuff & @marySalvi this was in the 'done' column for the study page squad board, but the issue is still open. 
I think this is done & can be closed. Can you confirm?

**Comment by ssarrafan** [comment] 2024-02-22 22:25
Mike and Mary confirmed this can be closed at the infra sync meeting today.  Closing issue.

**Closed by ssarrafan** 2024-02-22 22:25 UTC
